# Site
name: 'FACT.'
description: 'FACT abbreviation for Finance Accounting and Technology is a blogging for Finance, Accounting and FinTech Enthusiast.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blogs'
include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Siddharth:
      name:           Siddharth
      site:           https://siddharthshashikar.github.io/
      github:         https://github.com/siddharthshashikar/
      linkedin:       https://www.linkedin.com/in/siddharth-shashikar/
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Siddharth, the author of FACT. I'm a finance and money enthusiast, currently exploring different fields related to finance, loves to keep myself occupied with books, netflix & doodling. "
      email:          'siddharth.shashikar.1@gmail.com'

      
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Siddharth Shashikar
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]